In [ ]:
#Total 10 cities
'''
1.san diego
2.albuquerque
3.colorado
4.philadelphia
5.Indianapolis
6.las vegas
7.washington
8.Miami
9.New york
10.San Francicso
'''

In [1]:
from bs4 import BeautifulSoup
import requests
import urllib.parse
import pandas as pd
import numpy as np

In [2]:
#just change the website according to the City
websites='https://www.trulia.com/NM/Albuquerque/'

In [ ]:
bedroom=[]
bathroom=[]
sqft=[]
price=[]
parking=[]
address=[]
yearbuild=[]

pages=list(range(1,31))# First Check the total page number in the website
for page in pages:
    website=websites+str(page)+"_p/"
    print(website)
    try:
        request=requests.get(website)
        soup=BeautifulSoup(request.content,'html.parser')
        allresult_links=soup.find_all('li',{'class':'SearchResultsList__WideCell-b7y9ki-2'})
        data=[]
        for i in allresult_links:
            if i.has_attr('data-testid'):
                data.append(i)
        all_links=[]
        for d in data:
            for link in d.find_all('div',{'data-testid':'property-card-details'}):
                all_links.append('https://www.trulia.com'+link.find('a').get('href'))
        for link in all_links:
            request=requests.get(link)
            soup=BeautifulSoup(request.content,'html.parser')
            ##address
            try:
                address.append(soup.find('h1',{'class':'HomeSummaryShared__AddressH1-mmeem6-2 lalEGj'}).get_text())
            except:
                address.append("")
            ##price
            try:
                price.append(soup.find('div',{'class':'Text__TextBase-sc-1cait9d-0-div Text__TextContainerBase-sc-1cait9d-1 nBoMt'}).get_text())
            except:
                price.append("")
            ##bedroom
            try:
                bedroom.append(soup.find('div',{'data-testid':'home-summary-size-bedrooms'}).get_text())
            except:
                bedroom.append("")
            ##bathroom
            try:
                bathroom.append(soup.find('div',{'data-testid':'home-summary-size-bathrooms'}).get_text())
            except:
                bathroom.append("")
            ##Sqft
            try:
                sqft.append(soup.find('div',{'data-testid':'home-summary-size-floorspace'}).get_text())
            except:
                sqft.append("")
            ##parking
            try:
                parking.append(soup.find('div',string='Parking').findNext('div').get_text())
            except:
                parking.append("")
            ##yearbuild
            try:
                yearbuild.append(soup.find('div',{'class':'Text__TextBase-sc-1cait9d-0-div Text__TextContainerBase-sc-1cait9d-1 cTGlQX'}).get_text())
            except:
                yearbuild.append("")
            
    except:
        print("Page not exist"+website)

https://www.trulia.com/NM/Albuquerque/1_p/
https://www.trulia.com/NM/Albuquerque/2_p/

In [7]:
#if any page not access due to internet connection then insert page number in the missing list
missing=[25]
for miss in missing:
    website=websites+str(miss)+"_p/"
    print(website)
    try:
        request=requests.get(website)
        soup=BeautifulSoup(request.content,'html.parser')
        allresult_links=soup.find_all('li',{'class':'SearchResultsList__WideCell-b7y9ki-2'})
        data=[]
        for i in allresult_links:
            if i.has_attr('data-testid'):
                data.append(i)
        all_links=[]
        for d in data:
            for link in d.find_all('div',{'data-testid':'property-card-details'}):
                all_links.append('https://www.trulia.com'+link.find('a').get('href'))
        for link in all_links:
            request=requests.get(link)
            soup=BeautifulSoup(request.content,'html.parser')
            ##address
            try:
                address.append(soup.find('h1',{'class':'HomeSummaryShared__AddressH1-mmeem6-2 lalEGj'}).get_text())
            except:
                address.append("")
            ##price
            try:
                price.append(soup.find('div',{'class':'Text__TextBase-sc-1cait9d-0-div Text__TextContainerBase-sc-1cait9d-1 nBoMt'}).get_text())
            except:
                price.append("")
            ##bedroom
            try:
                bedroom.append(soup.find('div',{'data-testid':'home-summary-size-bedrooms'}).get_text())
            except:
                bedroom.append("")
            ##bathroom
            try:
                bathroom.append(soup.find('div',{'data-testid':'home-summary-size-bathrooms'}).get_text())
            except:
                bathroom.append("")
            ##Sqft
            try:
                sqft.append(soup.find('div',{'data-testid':'home-summary-size-floorspace'}).get_text())
            except:
                sqft.append("")
            ##parking
            try:
                parking.append(soup.find('div',string='Parking').findNext('div').get_text())
            except:
                parking.append("")
            ##yearbuild
            try:
                yearbuild.append(soup.find('div',{'class':'Text__TextBase-sc-1cait9d-0-div Text__TextContainerBase-sc-1cait9d-1 cTGlQX'}).get_text())
            except:
                yearbuild.append("")
            
    except:
        print("Page not exist"+website)

https://www.trulia.com/CA/San_Diego/25_p/

In [8]:
dic={
    'Bedroom':bedroom,
    'Bathroom':bathroom,
    'Sqft':sqft,
    'Price':price,
    'Parking':parking,
    'Address':address,
    'Yearbuild':yearbuild
}

In [9]:
#Creating DataFrame
df=pd.DataFrame(dic)

In [10]:
df.head()

,Bedroom,Bathroom,Sqft,Price,Parking,Address,Yearbuild
0,2 Beds,2 Baths,"1,275 sqft","$339,000",No Info,"390 San Antonio Ave #13San Diego, CA 92106",1965
1,2 Beds,2 Baths,896 sqft,"$511,900",Garage,"4615 Pico St #8San Diego, CA 92109",2004
2,3 Beds,2 Baths,956 sqft,"$450,000",Garage,"1927 Pueblo StSan Diego, CA 92113",1925
3,2 Beds,2 Baths,"1,466 sqft","$169,900",No Info,"1951 47th St #146San Diego, CA 92102",2014
4,3 Beds,2 Baths,"1,918 sqft","$999,000",Open Parking,"3610 Mount Aladin AveSan Diego, CA 92111",1959

In [11]:
df.shape

(1549, 7)

In [15]:
df.duplicated().sum()

230

In [18]:
#Removing Duplicate Rows
df.drop_duplicates(inplace=True)

In [19]:
df

,Bedroom,Bathroom,Sqft,Price,Parking,Address,Yearbuild
0,2 Beds,2 Baths,"1,275 sqft","$339,000",No Info,"390 San Antonio Ave #13San Diego, CA 92106",1965
1,2 Beds,2 Baths,896 sqft,"$511,900",Garage,"4615 Pico St #8San Diego, CA 92109",2004
2,3 Beds,2 Baths,956 sqft,"$450,000",Garage,"1927 Pueblo StSan Diego, CA 92113",1925
3,2 Beds,2 Baths,"1,466 sqft","$169,900",No Info,"1951 47th St #146San Diego, CA 92102",2014
4,3 Beds,2 Baths,"1,918 sqft","$999,000",Open Parking,"3610 Mount Aladin AveSan Diego, CA 92111",1959
...,...,...,...,...,...,...,...
1543,5 Beds,3 Baths,"2,348 sqft","$1,150,000",2 Car Garage,"4836 Cannington DrSan Diego, CA 92117",1976
1544,3 Beds,2 Baths,"1,771 sqft","$1,128,000",2 Car Garage,"5472 Hewlett DrSan Diego, CA 92115",1958
1545,,,,"$175,000",No Info,"Spring Canyon Rd #35Santee, CA 92071",No Info
1547,4 Beds,5 Baths,"3,415 sqft","$3,650,000",3 Car Garage,"5266 Grand Del Mar Way #2San Diego, CA 92130",2020
1548,5 Beds,4 Baths,"3,358 sqft","$2,799,900",Garage,"1864 Sunset BlvdSan Diego, CA 92103",1936

In [20]:
#change the according to the dataset
df.to_csv('San_Diego.xlsx',index=False)